gallery/gallery/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    # path('users/', include('accounts.urls', namespace='accounts')),
    path('', include('pictures.urls', namespace='pictures')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gallery/pictures/urls.py
from django.contrib import admin
from django.urls import path

from .views.pictures import PicturesIndexView

app_name = 'pictures'

urlpatterns = [

    path('', PicturesIndexView.as_view(), name='index'),
]

gallery/accounts/models/Account.py
from django.db import models
from django.contrib.auth.models import User


class Account(models.Model):

    user = models.OneToOneField(
        User,
        on_delete=models.PROTECT,
        related_name='Пользователь',
        verbose_name='аккаунт'
    )

    name = models.CharField(
        max_length=20,
        default=None,
        blank=False,
        verbose_name="Имя"
    )

    surname = models.CharField(
        max_length=20,
        default=None,
        blank=False,
        verbose_name="Фамилия"
    )


    email = models.EmailField(
        max_length=30,
        unique=True,
        blank=False,
        default=None,
        verbose_name='Имейл'
    )

    def __str__(self):
        return "%s %s" % (self.name, self.surname)

gallery/pictures/models/Comment.py
from django.db import models


class Comment(models.Model):
    text = models.TextField(
        verbose_name="текст коммента",
        max_length=100,
        blank=True,
        default=None
    )

    account = models.ForeignKey('accounts.Account',
                             related_name="comment_user",
                             on_delete=models.CASCADE,
                             verbose_name='комменты-пользователи'

                             )

    picture = models.ForeignKey('pictures.Picture',
                                related_name="picture_user",
                                on_delete=models.CASCADE,
                                verbose_name="комменты-картинки"
                                )

    rating = models.DecimalField(
        max_digits=2,
        decimal_places=1,
        blank=False,
        default=None
    )

    date = models.DateField(
        verbose_name="Дата добавления",
        null=True,
        blank=True,
        default=None
    )

gallery/pictures/models/Picture.py
from django.db import models


class Picture(models.Model):
    account = models.ForeignKey('accounts.Account',
                                related_name='picture_account',
                                on_delete=models.CASCADE,
                                )

    comment = models.ForeignKey('pictures.Comment',
                                related_name='picture_comment',
                                on_delete=models.CASCADE
                                )

    title = models.CharField(
        verbose_name="Заголовок",
        max_length=100,
        blank=False,
        default=None
    )
    average_rating = models.DecimalField(
        verbose_name="Средняя оценка",
        max_digits=3,
        decimal_places=1,
        blank=True,
        default=None,
    )
    date = models.DateField(
        verbose_name="Дата добавления",
        auto_now_add=True
    )

gallery/pictures/forms/picture_form.py
from django.forms import forms
from ..models.Picture import Picture


class PictureUploadForm(forms.ModelForm):
    title = forms.CharField(
        label='Заголовок',
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'Введите название'
        })
    )

    picture = forms.ImageField(label='Картинка', required=False)

    class Meta:
        model = Picture
        include = ["title", "picture"]

gallery/pictures/views/pictures.py
from django.views.generic import ListView
from pictures.models import Picture


class PicturesIndexView(ListView):
    template_name = 'pictures/index.html'
    context_object_name = 'pictures'
    # paginate_by = 10
    # paginate_orphans = 1
    model = Picture
    ordering = ['date']

    def get_context_data(self, **kwargs):
        return super().get_context_data(**kwargs)

gallery/pictures/templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
    <link rel ="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <nav class="navbar" >
        <ul class="menu">
            <li><a href="{% url 'pictures:index' %}">На главную</a></li>
            <li><a href="#">Комментарии:</a></li>
            <li><a href="#">Список пользователей</a></li>
            {% if user.is_authenticated %}
           {% block menu_links %}{% endblock %}
    <li class="menu-right"><a href=""#"" class="nav-link">Выход</a></li>
    <li class="menu-right">Привет, <a href="#"> {{ user.username }}</a>!</li>
       {% else %}
           <li class="menu-right"><a href="#" class="nav-link">Вход</a></li>
        <li class="menu-right"><a href="#" class="nav-link">Регистрация</a></li>
       {% endif %}
        </ul>
    </nav>
    <div class="container">
    {% block content %}{% endblock %}</div>


</body>
</html>

gallery/pictures/templates/partials/_form.html
{% for error in form.non_field_errors %}
    <p class="form-error">{{ error }}</p>
{% endfor %}

{% for field in form %}
    <div class="form-group {% if field.errors %}error{% endif %}">
        <label for="{{ field.id_for_label }}">{{ field.label }}{% if field.field.required %}<span class="required-indicator"> *</span>{% endif %}</label>
        {% if field.errors %}
            {{ field }}
            {% for error in field.errors %}
                <small class="form-text">{{ error }}</small>
            {% endfor %}
        {% else %}
            {{ field }}
        {% endif %}
    </div>
{% endfor %}

gallery/pictures/templates/pictures/index.html
{% extends 'base.html' %}

{% block title %}
    Lombard CRM
{% endblock %}

{% block heading %}
    Добро пожаловать
{% endblock %}

{% block content %}
{% for picture in pictures %}
         {% if picture.status == False %}
        {% else %}
            <tr>
                <td>{{ picture.id }}</td>
                <td>{{ picture.title }} </td>
                <td>{{ picture.date|date:'d.m.Y' }}</td>
                <td>{{ picture.image}}</td>
                <td><a href="#" >Детали</a></td>
                </tr>
        {% endif%}
        {% empty %}
            <tr>
                <td colspan="10">
                    <div class="no-content">
                        <p class="no-content-text">Картинок пока нет</p>
                    </div>
                </td>
            </tr>
        {% endfor %}
{% endblock %}